[Switch] Create Switch API for virtual keyboards
Homebrodot/Godot pull request #10
Opened 2024-01-22 18:43 UTC by halotroop2288

Adds a new `NintendoSwitch` global singleton for opening different types of virtual keyboard supported by Horizon OS.

This can be expanded to support other Switch-specific features later on.

I also went ahead and fixed a few bugs with the `.gitignore` and made sure the ELF file gets deleted after the NRO is generated.

This is currently untested.

2024-01-25 23:18 UTC, hokaze requested changes
I figured out why the keyboard wasn't showing in the test suite.

When the code was moved over from os_switch.cpp to api.cpp, there's some code for initialising the software keyboard that was shifted out of OS_Switch::run and into NintendoSwitch::initialize_software_keyboard():

...however, the initialize_software_keyboard() method isn't actually called anywhere, so the keyboard never gets setup properly.

In my own local changes to test and confirm this theory, I just put
`NintendoSwitch::get_singleton()->initialize_software_keyboard();`
On line 351 of os_switch.cpp below main_loop->init(), as that's where that code was previous to being moved to that method.

----

Other Issues I've just spotted:
- For some reason, the first 2 characters of the TextEdit node can't be deleted, the keyboard acts as if it can't go any further left, either when deleting or when using L/R to move the cursor left/right
- when focusing on the textedit to open the keyboard, I often get it automatically adding either an extra "g" or whatever the last character that was typed onto the end, sometimes 2 of such characters. They can be deleted as normal, but it only happens when the textedit is focused, not when opening the number pad
- more a complaint with the libnx docs, but I have no idea what the difference is between the all languages keyboard and the default one opened on focusing the textedit - both have the same sets of characters by default and both have the option in the bottom left to change the keyboard layout
- switch keyboard layout to other languages has the layout update correctly, but the actual characters entered into the text edit don't match the updated layout - tested this with german and japanese hiragana keysets, a lot of the time they just put Ã, a space, a unicode character like ©, etc instead of the actual character selected - this could be a problem with either the keyboard or with the text encoding on the textedit (although I think Godot uses UTF-8 by default, so should normally be fine)

I didn't notice anything massively amiss with the numpad, at least?

Don't have any lead on the keyboard inserting phantom keypresses or not letting you navigate all the way to the start of the string, as I didn't encounter either of those issues on the initial PR we did together for fixing Switch virtual keyboard

2024-01-26 01:39 UTC, halotroop2288 commented
The string length had to be adjusted for the NUL-terminator (NUL = 3 characters)

This solves the issue of not being able to remove all of the text.

[![image](https://github.com/Homebrodot/Godot/assets/30361266/f6b8a09b-eb0b-4b3c-b2a5-d838865e17e7)](https://switchbrew.github.io/libnx/structSwkbdChangedStringArg.html#details)

2024-01-26 02:20 UTC, halotroop2288 commented
The check needed to be for string length greater than zero, not any length other than zero. That's how we were getting erroneous characters when it started.

2024-01-26 22:08 UTC, halotroop2288 commented
OK, I'm going to merge this for now just to get it over with, but my next PR will likely move this to its own module. I just want to have it out of the way for now.

2024-01-26 22:08 UTC, merged